//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBetView.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IBetService")]
    public interface IBetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/ConfirmBet", ReplyAction="http://tempuri.org/IBetService/ConfirmBetResponse")]
        void ConfirmBet(MyBetModel.Model.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/ConfirmBet", ReplyAction="http://tempuri.org/IBetService/ConfirmBetResponse")]
        System.Threading.Tasks.Task ConfirmBetAsync(MyBetModel.Model.Bet bet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBetServiceChannel : MyBetView.ServiceReference3.IBetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BetServiceClient : System.ServiceModel.ClientBase<MyBetView.ServiceReference3.IBetService>, MyBetView.ServiceReference3.IBetService {
        
        public BetServiceClient() {
        }
        
        public BetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ConfirmBet(MyBetModel.Model.Bet bet) {
            base.Channel.ConfirmBet(bet);
        }
        
        public System.Threading.Tasks.Task ConfirmBetAsync(MyBetModel.Model.Bet bet) {
            return base.Channel.ConfirmBetAsync(bet);
        }
    }
}
